# -*- coding: utf-8 -*-
"""EDA PROJECT-Heart Disease Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LtOA-WqG9Lt-E4r9V4CdBa8POlMBwoiS

#**EDA-PROJECT**

#**HEART DISEASE ANALYSIS**

#STEP 1- Importing Libraries

*   PANDAS:Handles data ingestion, cleaning, and structuring through highly optimized DataFrames.
*   NUMPY:Powers the underlying vectorization and multi-dimensional array operations for fast numerical processing.
*   MATPLOTLIB:Acts as the low-level object-oriented engine used to initialize figures, manage subplots, and fine-tune chart aesthetics.
*   SEABORN:Provides a high-level abstraction layer over Matplotlib specifically designed for mapping statistical distributions and interactions directly to plot properties.
"""

#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mlt
import seaborn as sns

"""#STEP 2- Loading Data

*   Loaded CSV File using PANDAS Library.
*   Used pd.read_csv() function.
*   pd.read_csv():Helps in opening the CSV file, reading the data from that file, and turning it into a neat table inside Python.







"""

#loading data
disease_raw_df=pd.read_csv("/content/Heart_Disease_Prediction[1].csv")

"""#STEP 3- Understanding Data

*   In this section, I have done data exploration like what all is there present inside the CSV File.
*   Here, I have used 3 functions i.e. describe(),info(), head().
*   Use of these functions:-
1.  df.describe(): Gives a quick summary of the math statistics for the numbers, like the average, minimum, and maximum values of each column.
2.  df.info(): Tells the technical details of the table, like the total number of rows, column names, and if any data is missing.
3.  df.head(): Shows the very first few(basically 5) rows of your table so we can see what our data actually looks like.




"""

#checking data present inside this csv file
disease_raw_df.describe()

disease_raw_df.info()

#checking head values
disease_raw_df.head()

"""# STEP 4-Data Preprocessing & Cleaning

*   Data Preprocessing- The comprehensive process of transforming raw, unorganized data into a structured and clean format suitable for analysis or machine learning models.
*   Data Cleaning- A specific subset of preprocessing focused entirely on identifying and fixing errors, handling missing (null) values, and removing duplicate records to ensure data accuracy.

**4.1 Data Preprocessing**

*   In this dataset, the original columns lacked descriptive categories for gender and age groups, which I created to improve clarity for my analysis. *   First, because the original Sex column (Column B) encoded data numerically as 0 and 1, I inserted an adjacent column named Gender and applied the Excel formula =IF(B2=1,"Male","Female") to clearly convert 1 into "Male" and 0 into "Female".
*   Second, to simplify individual numerical ages into broader, more meaningful lifespans, I added an Age Group column next to the Age column (Column A). Using a nested Excel conditional statement, =IF(A2<=34,"Young",IF(A2<=50,"Middle",IF(A2<=64,"Senior","Elderly"))), I successfully binned the continuous ages into four specific macro-categories: Young (ages 18–34), Middle (ages 35–50), Senior (ages 51–64), and Elderly (ages 65 and older).

Now I have loaded the corrected dataset which has all the columns present.
"""

#loading the corrected dataset
heart_disease_df=pd.read_csv("/content/Heart_Disease_Prediction.csv")

"""To check are all columns present inside the table I have used df.column function.

*   df.column- It gives a quick list of all the column names present in the dataset table so you know exactly what variables you have to work with.


"""

#checking the column header
heart_disease_df.columns

"""**4.2 Data Cleaning**

*   In this section, I have used 2 functions to check null values and duplicate values.
*   df.isnull().sum()- It counts and shows the exact number of missing (blank) values in each column of the table so we know where our data is incomplete.
*   df.duplicated().sum(): It searches through the table to find identical rows and gives the total count of duplicate records so we can see if we have repeated data.


"""

# checking for duplicate and null values

heart_disease_df.isnull().sum()

heart_disease_df.duplicated().sum()

"""There is neither any null value nor any duplicate. Hence, the data is already clean.

#STEP 5- Data Visualization & Analysis

*   Data visualization means turning lists of numbers and text into easy-to-read charts, graphs, and maps. It helps your eyes instantly spot hidden patterns, trends, and unexpected mistakes that you would miss by just looking at a raw spreadsheet. Essentially, it translates complex data into a clear visual story that anyone can understand at a glance.

*   I divided the columns under different sections for analysis.
"""

#selecting columns to represent data graphically
selected_columns=[
    #understanding patient demographics
    'Age Group',
    'Gender',
    #identifying risk factors
    'Cholesterol',
    'Max HR',
    'BP'
    #analyzing feature interactions
    'Heart Disease',
    'BP',
    #analyzing symptoms & clinical tests
    'Chest pain type',
    'EKG results',
    'FBS over 120']

"""**Plotting graphs, charts, and plots.**

Question1: What is the age distribution of the patients in this study? Is it skewed toward older or younger populations?
"""

plt.figure(figsize=(12, 6))
sns.histplot(data=heart_disease_df, x='Age Group',bins=20,kde=True,color='g')
plt.title('Age Distribution of Patients')
plt.xlabel('Age Group')
plt.ylabel('Frequency')

"""The chart shows that the dataset is heavily skewed toward older populations, with the vast majority of patients falling into the Senior and Middle age categories. In contrast, there are very few elderly patients and almost no young patients included in the study. Therefore, the data primarily reflects individuals in their mid-career to later life stages.

Question2: What is the gender breakdown of the patients? Are males or females more represented?
"""

plt.figure(figsize=(12, 6))
sns.barplot(x=heart_disease_df['Gender'].value_counts().index,y=heart_disease_df['Gender'].value_counts())
plt.title('Gender Distribution of Patients')
plt.xlabel('Gender')
plt.ylabel('Frequency')

"""Based on the barplot, there are significantly more male patients in the dataset than female patients. Therefore, males are much more represented, making up the vast majority of the total individuals studied.

Question3: Do patients diagnosed with heart disease tend to have significantly higher cholesterol levels compared to those who don't?
"""

plt.figure(figsize=(12, 6))
sns.barplot(x='Heart Disease',y='Cholesterol',hue='Gender',data=heart_disease_df)
plt.title('Cholesterol Distribution by Heart Disease')

"""The chart reveals that patients with heart disease ("Presence") generally have noticeably higher cholesterol levels compared to those without it ("Absence"). Additionally, regardless of heart disease status, female patients consistently display higher average cholesterol levels than male patients.

Question3: Does the maximum heart rate achieved drop as a patient ages, and does this trend differ based on whether they have heart disease?
"""

plt.figure(figsize=(12, 6))
sns.lineplot(x='Age',y='Max HR',hue='Heart Disease',data=heart_disease_df)
plt.title('Age vs. Maximum heart rate')

"""The chart confirms that maximum heart rate generally drops as patients get older, showing a downward trend for both groups from left to right. However, this trend differs because patients with heart disease ("Presence", the blue line) consistently maintain a lower maximum heart rate across almost all age groups compared to healthy patients ("Absence", the orange line).

Question4: How does the relationship between Age and Blood Pressure change when comparing men versus women?
"""

plt.figure(figsize=(12, 6))
sns.scatterplot(x='Age',y='BP',hue='Gender',data=heart_disease_df)
plt.title('Blood Pressure vs. Age')

"""the scatterplot shows a general upward trend, indicating that blood pressure tends to increase as patients get older. This rising pattern is quite similar for both men and women, with both genders widely and evenly mixed across the age groups.

Question5: Which type of chest pain is most commonly reported by patients who are ultimately diagnosed with heart disease?
"""

plt.figure(figsize=(12, 6))
sns.countplot(x='Chest pain type',hue='Heart Disease',data=heart_disease_df)
plt.title('Chest Pain Types by Heart Disease')

"""The countplot shows shows that chest pain type 4 is by far the most commonly reported type among patients diagnosed with heart disease ("Presence"). In contrast, patients who do not have heart disease ("Absence") are most frequently associated with chest pain type 3.

Question6: Does having a high fasting blood sugar level significantly correlate with a positive heart disease diagnosis?
"""

plt.figure(figsize=(12, 6))
sns.countplot(x='FBS over 120',hue='Heart Disease',data=heart_disease_df)
plt.title('Fasting blood sugar level by Heart Disease')

"""The countplot shows that a high fasting blood sugar level (value 1) does not strongly correlate with a positive heart disease diagnosis, as the number of patients remains low and evenly split between presence and absence. Instead, the vast majority of patients in both groups actually have lower fasting blood sugar levels (value 0).

Question7: How do the results of an electrocardiographic test differ between patients with and without heart disease?
"""

plt.figure(figsize=(12, 6))
sns.countplot(x='EKG results',hue='Heart Disease',data=heart_disease_df)
plt.title('Electrocardiographic test by Heart Disease')

"""The countplot shows that patients without heart disease ("Absence") are most likely to have an EKG result of 0. On the other hand, patients diagnosed with heart disease ("Presence") are significantly more likely to have an EKG result of 2, making up the majority of that category.

#STEP 6-Conclusion of Analysis


*   Overall, this analysis reveals a few clear patterns when it comes to risk factors for heart disease. We can see that the dataset mostly consists of middle-aged and older adults, with a much higher representation of male patients overall. When looking closely at the medical indicators, patients diagnosed with heart disease generally show noticeably higher cholesterol levels, structurally lower maximum heart rates across all age groups, and distinct abnormalities in their EKG test results.
"""