# -*- coding: utf-8 -*-
"""Final_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aY9cNHvuZYHJ8Mg4boGr_1ycq8xX_n2s
"""

# importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mlt
import seaborn as sns

#reading csv file using pyhton
raw_df=pd.read_csv("/content/loan_data.csv")

#checking information present in this
raw_df.info()

raw_df.head()

#the column names are not understandable. also we need to understand the data.
#understanding each column
#credit.policy=meets lending club criteria(it is present as 1 and 0)
#purpose=purpose of taking loan
#int.rate=interest rate
#installment=monthly payment amount
#log.annual.inc=the natural log of annual income
#dti=debt-to-income ratio
#fico=credit score(higher fico=better grade)
#days.with.cr.line=days the borrower has had a credit line
#revol.bal=unpaid credit balance
#revol.util=percentage of credit line used
#inq.last.6mths=credit inquiries in last 6 months
#deling.2yrs=times 30+ days past due in last 2 years
#pub.rec=number of derogatory public records
#not.fully.paid=default status(given in 0 and 1)

#the column names need to be changed to make them more understandable
#this i have done using excel and the data given in 0s and 1s has been changed to "yes"/"no" and "paid back"/"defaulted" accordingly
#credit.policy(0=no,1=yes)-->meets_credit_policy
#purpose=loan_purpose
#int.rate=interest_rate
#installment=monthly_installment
#log.annual.inc=the natural log of annual income
#dti=dti_ratio
#days.with.cr.line=credit_history_days
#revol.bal=revolving_balance
#revol.util=credit_utilization_rate
#inq.last.6mths=recent_credit_inquiries
#deling.2yrs=past_due_2yrs
#pub.rec=public_records
#not.fully.paid(0=paid back,1=defaulted)=default_status

#because the annual income was in natural logarithm form i created a new column namely annual_income used formula =EXP(E2) it converted the log form into $ .then added one more column named it income_band divided the annual income into different categories using formula =IFS(F2<=30000, "Low Income (<$30k)", F2<=60000, "Medium-Low ($30k-$60k)", F2<=100000, "Medium-High ($60k-$100k)", F2>100000, "High Income (>$100k)") then we were provided with fico score therefore i created a column named loan_grade according to the fico scores divided grades into a,b,c,d using formula =IF(I2>=750,"Grade A(Excellent Risk)",IF(I2<=749,"Grade B(Very Good Risk)",IF(I2>=660,"Grade C(Good Risk)","Grade D(Below High Risk")))

data_df=pd.read_excel("/content/loan_data_new.xlsx")

data_df.describe()

data_df.info()

data_df.columns

data_df.head()

data_df.duplicated().sum()

data_df.isnull().sum()

#the data is cleaned

