# -*- coding: utf-8 -*-
"""Project1-IPL Data Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oEJv1m03xLGY68cfS9Jz1d9ZceP-8Zwc

# CLEANING DATASET
"""

import pandas as pd
import numpy as np
df=pd.read_csv("/content/matches.csv")
print(df.head())

df.isnull().sum()

df[df.isnull().any(axis=1)]

df.drop('umpire3', axis=1, inplace=True)

df = df.dropna()

df.isnull().sum()

df.duplicated().sum()

df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

df.to_csv("Cleaned_matches.csv",index=False)

"""# ANALYZING DATA"""

#TOP RUNNER SCORER
runs=df.groupby('winner')['win_by_runs'].sum()
top_teams=runs.sort_values(ascending=False)
print("******************TOP RUNNER SCORER*********************")
print(top_teams)
print("********************************************************")

#TEAMS WITH MOST WICKETS
wickets=df.groupby('winner')['win_by_wickets'].sum()
top_teams=wickets.sort_values(ascending=False)
print("****************TEAMS HAVING MOST WICKETS*****************")
print(top_teams)
print("**********************************************************")

#WINNING PERCENTAGE
t1=df['team1'].value_counts()
t2=df['team2'].value_counts()
total=t1.add(t2, fill_value=0)
wins=df['winner'].value_counts()
winning_percentage=(wins/total)*100
data= winning_percentage.sort_values(ascending=False)
print("******************** TEAM WINNING PERCENTAGE ********************")
print(data)
print("*****************************************************************")

#TOSS IMPACT ANALYSIS
total=len(df)
toss_wins=(df['toss_winner']==df['winner']).sum()
print("*****************TOSS IMPACT ANALYSIS*************************")
print(f"Total Matches:{total}")
print(f"Matches Won:{toss_wins}")
result=(toss_wins/total)*100
print(f"Toss Impact Percentage:{result:.2f}%")
print("**************************************************************")